version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/entrypoint.sh"] # Usar um script de entrada
    volumes:
      - .:/app # Para desenvolvimento local, remova para produção
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=core_platform.settings
      - NEXT_PUBLIC_API_URL=http://web:8000
      - FRONTEND_URL=http://localhost:3000
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped