version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=core_platform.settings
      - NEXT_PUBLIC_API_URL=https://frontend-tccplatform-sesy.vercel.app/
      - FRONTEND_URL=https://frontend-tccplatform-sesy.vercel.app/
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
